markdown_extensions:
- admonition
- attr_list
- md_in_html
- toc:
    permalink: true
- pymdownx.details
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
- Overview: index.md
- Getting Started: getting_started.md
- Custom Resources:
  - Overview: crds/index.md
  - TalosCluster: crds/taloscluster.md
  - TalosContolPlane: crds/taloscontrolplane.md
  - TalosWorker: crds/talosworker.md
  - TalosMachine: crds/talosmachine.md
  - TalosEtcdBackup: crds/talosetcdbackup.md
  - TalosEtcdBackupSchedule: crds/talosetcdbackupschedule.md
- Operator Manual:
  - Overview: operator_manual/index.md
  - Reconciliation Modes: operator_manual/reconciliation_modes.md
  - Reconciliation States: operator_manual/reconciliation_states.md
  - Modes: operator_manual/modes.md
  - Upgrading Versions: operator_manual/upgrade_versions.md
  - Importing Existing Resources: operator_manual/import_existing_resources.md
  - Booting Talos Automatically: operator_manual/talos_auto_boot.md
  - State Secret: operator_manual/state_secret.md
  - Customizing the Machine Config: operator_manual/customizing_machine_config.md
  - Drift Detection: operator_manual/drift_detection.md
- Upgrading:
  - Overview: upgrading/index.md
  - v0.3.4: upgrading/v0.3.4.md

- metrics.md
- contributing.md
- roadmap.md
- Releases ⧉: https://github.com/alperencelik/talos-operator/releases

repo_url: https://github.com/alperencelik/talos-operator
repo_name: alperencelik/talos-operator
site_name: talos-operator
strict: true
theme:
  favicon: images/logo.png
  font:
    text: Inter
    code: JetBrains Mono
  logo: images/logo.png
  name: material
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - header.autohide
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - toc.follow
  palette:
  - media: '(prefers-color-scheme: light)'
    primary: deep-orange
    accent: orange
    scheme: default
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    primary: deep-orange
    accent: orange
    scheme: slate
    toggle:
      icon: material/weather-night
      name: Switch to light mode

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      lang: en
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
  - mike:
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/alperencelik/talos-operator